language: go

arch:
  - AMD64
  - ppc64le

go_import_path: github.com/d4l3k/messagediff

os:
  - linux

go:
  - 1.14.x
  - 1.15.x
  - tip

allow_failures:
  - go: tip


before_install:
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=example.coverprofile ./example
  - go test -v -coverprofile=main.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile
